### ISSUE TITLE
[ruby] ruby app fails when starting

### ISSUE THREAD

**Issue by v1v** [elastic/apm-integration-testing#1017]
### What

Nightly builds for the master branch are failing for the branch:2.x of the ruby agent.

### Error

```
Using elastic-apm 2.12.0 from https://github.com/elastic/apm-agent-ruby.git (at 2.x@1c13d9e)
Bundle complete! 8 Gemfile dependencies, 62 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from i18n:
HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.
If you are upgrading your Rails application from an older version of Rails:
Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.
If you are starting a NEW Rails application, you can ignore this notice.
For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
/usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/config/options.rb:9:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/config/options.rb:90:in `new'
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/config/options.rb:90:in `block in load_schema'
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/config/options.rb:89:in `each'
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/config/options.rb:89:in `map'
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/config/options.rb:89:in `load_schema'
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/config.rb:91:in `initialize'
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/railtie.rb:16:in `new'
	from /usr/local/bundle/bundler/gems/apm-agent-ruby-1c13d9e35a1c/lib/elastic_apm/railtie.rb:16:in `block in <class:Railtie>'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
```

### How to reproduce

```
python3 scripts/compose.py start 8.0.0   --apm-server-build https://github.com/elastic/apm-server.git@master --build-parallel --ruby-agent-version='2.x' --ruby-agent-version-state='github'   --no-apm-server-dashboards   --no-apm-server-self-instrument   --no-kibana   --with-agent-ruby-rails   --force-build   --no-xpack-secure   --apm-log-level=debug
```

### Reasons

ruby:latest docker image has been updated recently 

![image](https://user-images.githubusercontent.com/2871786/103771553-d99bb280-501f-11eb-8603-ae17be2441ef.png)

And actually matches with the exact date when things started to fail apart.

### Actions

* Fix the incompatibility with ruby:3 for the 2.x branch

cc @estolfo

**Comment by estolfo** [comment]
Following our discussion, I think it's ok to use ruby 2.x for agent 2.x, as we don't have plans to do a 2.x release to support ruby 3.0 (the latest, released less than two weeks ago). So the "Short term, fix the version to ruby:2" can be the long-term solution.

**Comment by v1v** [comment]
It's required to fix the 7.x branch, but unfortunately it requires a new implementation since both branches have diverged quite a bit

**Comment by kuisathaverat** [comment]
it affects also branch 6.x, we should test the latest compatible version that I guess is 2.11

```
[2021-01-11T03:14:14.190Z] ----
[2021-01-11T03:14:14.190Z] /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/config/options.rb:9:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/config/options.rb:90:in `new'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/config/options.rb:90:in `block in load_schema'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/config/options.rb:89:in `each'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/config/options.rb:89:in `map'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/config/options.rb:89:in `load_schema'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/config.rb:91:in `initialize'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/railtie.rb:16:in `new'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/railtie.rb:16:in `block in <class:Railtie>'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
[2021-01-11T03:14:14.190Z] 	from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
[2021-01-11T03:14:14.190Z] 	from /app/testapp/config/environment.rb:5:in `<main>'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/elastic-apm-2.12.0/lib/elastic_apm/spies.rb:74:in `require'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
[2021-01-11T03:14:14.190Z] 	from config.ru:3:in `block in <main>'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:27:in `app'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:53:in `start'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
[2021-01-11T03:14:14.190Z] 	from <internal:kernel>:90:in `tap'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:142:in `perform'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
[2021-01-11T03:14:14.190Z] 	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
[2021-01-11T03:14:14.191Z] 	from /app/testapp/bin/rails:9:in `<top (required)>'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
[2021-01-11T03:14:14.191Z] 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
[2021-01-11T03:14:14.191Z] 	from /app/testapp/bin/spring:15:in `require'
[2021-01-11T03:14:14.191Z] 	from /app/testapp/bin/spring:15:in `<top (required)>'
[2021-01-11T03:14:14.191Z] 	from bin/rails:3:in `load'
[2021-01-11T03:14:14.191Z] 	from bin/rails:3:in `<main>'
```

**Comment by kuisathaverat** [comment]
Victor has a PR in place for branch 6.x so is resolved.
