### ISSUE TITLE
opbeans-rum fails to start on m1 laptops

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-integration-testing#1466]
Running `./scripts/compose.py start main --all-opbeans` yields the following error:

```
#5 15.93 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#5 15.93 
#5 16.86 2 packages can be upgraded. Run 'apt list --upgradable' to see them.
#5 16.86 
#5 16.86 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#5 16.86 
#5 17.35 E: Unable to locate package google-chrome-unstable
------
executor failed running [/bin/sh -c apt update -qq     && apt install -qq -y curl git gnupg libgconf-2-4 libxss1 libxtst6 python g++ build-essential --no-install-recommends     && curl -sSfkL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'     && apt update -qq     && apt install -qq -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont       --no-install-recommends     && rm -rf /var/lib/apt/lists/*     && rm -rf /src/*.deb]: exit code: 100
ERROR: Service 'opbeans-rum' failed to build : Build failed
Traceback (most recent call last):
  File "/Users/dariogieselaar/dev/apm-integration-testing/./scripts/compose.py", line 31, in <module>
    main()
  File "/Users/dariogieselaar/dev/apm-integration-testing/./scripts/compose.py", line 17, in main
    setup()
  File "/Users/dariogieselaar/dev/apm-integration-testing/scripts/modules/cli.py", line 209, in __call__
    self.args.func()
  File "/Users/dariogieselaar/dev/apm-integration-testing/scripts/modules/cli.py", line 586, in start_handler
    self.build_start_handler("start")
  File "/Users/dariogieselaar/dev/apm-integration-testing/scripts/modules/cli.py", line 751, in build_start_handler
    self.run_docker_compose_process(docker_compose_build + build_services)
  File "/Users/dariogieselaar/dev/apm-integration-testing/scripts/modules/cli.py", line 472, in run_docker_compose_process
    subprocess.check_call(docker_compose_cmd)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', '-f', '/Users/dariogieselaar/dev/apm-integration-testing/docker-compose.yml', 'build', '--pull', 'opbeans-java', 'opbeans-go', 'opbeans-rum', 'opbeans-python', 'opbeans-ruby', 'opbeans-node', 'opbeans-dotnet']' returned non-zero exit status 1.
```

I've not heard others complain about this so I'm assuming it's an error specific to m1/arm environments.

**Comment by jasonrhodes** [comment]
Ran into this myself today (also on M1). Noticed that some of the Dockerfile installation commands hard-code an amd64 requirement: 
https://github.com/elastic/apm-integration-testing/blob/03c8818/docker/opbeans/rum/Dockerfile#L9

@kuisathaverat is looking into some of the arch issues here.

**Comment by kuisathaverat** [comment]
Long history short, there is no `google-chrome` Debian package for ARM, I am waiting for confirmation that we can change it to Chromium
