### ISSUE TITLE
Enable Testing for ARM64 platform

### ISSUE THREAD

**Issue by odidev** [elastic/apm-integration-testing#1503]
Hi Team, 

I am working with Elastic APM on the Linux ARM64 platform. 

Although it seems currently testing for ARM64 is not included in the CI. Do you have any plan to include the ARM64 testing for Linux? 
If interested there are machines hosted which provides arm64 support and can be used i.e. [works on arm](https://github.com/WorksOnArm). 

Please share your views on the same. If required, I’ll be happy to contribute.

**Comment by v1v** [comment]
Hey @odidev , if you would like to help with that's awesome, there are a few questions to answer regarding:
- when the ARM64 testing should run (always, on a PR basis, scheduled)?
- should it run to validate the APM Agents too (similarly done with https://github.com/elastic/apm-integration-testing/blob/main/.ci/integrationTestSelector.groovy?
- what would you like to run for testing on ARM64?

The existing CI provides support for ARM64, that's something we use in some other places, like the one in https://github.com/elastic/apm-server/blob/f5f0272b1d18e42db75a14e3739deb6cc1d341e2/Jenkinsfile#L265-L281

Thanks

**Comment by kuisathaverat** [comment]
I recently fixed a couple of Docker images to run on Linux/arm64, I did not test all containers but the command `scripts/compose.py start 8.4.0-SNAPSHOT ---all-opbeans`  build/run the Stack and Opbeans on arm64 machines without issues, I think all the rest of containers must build on a arm64 machine, it is easy to test by running `.ci/scripts/all.sh` on a M1 machine, this will build all the Agents containers on arm64.

**Comment by odidev** [comment]
> * when the ARM64 testing should run (always, on a PR basis, scheduled)?

It would be nice if ARM64 tests run along with X64 tests. 

> * should it run to validate the APM Agents too (similarly done with https://github.com/elastic/apm-integration-testing/blob/main/.ci/integrationTestSelector.groovy?
> * what would you like to run for testing on ARM64?

I would like to run ARM64 testing for all the tests running for X64 including this: https://github.com/elastic/apm-integration-testing/blob/main/.ci/integrationTestSelector.groovy

**Comment by odidev** [comment]
I’m trying to run the apm integration tests on Jenkins CI. I removed the `NOTIFY_TO` and `JOB_GCS_BUCKET` credentials defined under environment in [Jenkinsfile](https://github.com/elastic/apm-integration-testing/blob/main/.ci/Jenkinsfile). But on running the build in CI, all the stages are getting skipped and giving the following error: 

 
``` 
Started by user Odidev 

 > /usr/bin/git rev-parse --resolve-git-dir /var/lib/jenkins/caches/git-c4264647fcfcf00b3c0ff76b02907011/.git # timeout=10 
Setting origin to https://github.com/odidev/apm-integration-testing 
 > /usr/bin/git config remote.origin.url https://github.com/odidev/apm-integration-testing # timeout=10 
Fetching origin... 
Fetching upstream changes from origin 
 > /usr/bin/git --version # timeout=10 
 > git --version # 'git version 2.34.1' 
 > /usr/bin/git config --get remote.origin.url # timeout=10 
using GIT_ASKPASS to set credentials credentials for testing 
 > /usr/bin/git fetch --tags --force --progress -- origin +refs/heads/*:refs/remotes/origin/* # timeout=10 
Seen branch in repository origin/5.x 
Seen branch in repository origin/6.x 
Seen branch in repository origin/7.x 
Seen branch in repository origin/8.x 
Seen branch in repository origin/main 
Seen branch in repository origin/revert-1435-apm_managed 
Seen branch in repository origin/update-go-version-20220328033908-main 
Seen 7 remote branches 
Obtained .ci/Jenkinsfile from 62a77f0a03e00ecf0a6c45ec3268e1aeca2cdc80 
Resume disabled by user, switching to high-performance, low-durability mode. 
Loading library apm@current 
Attempting to resolve current from remote references... 
 > /usr/bin/git --version # timeout=10 
 > git --version # 'git version 2.34.1' 
using GIT_ASKPASS to set credentials credentials for testing 
 > /usr/bin/git ls-remote -h -- https://github.com/odidev/apm-pipeline-library # timeout=10 
Could not find current in remote references. Pulling heads to local for deep search... 
 > /usr/bin/git rev-parse --resolve-git-dir /var/lib/jenkins/caches/git-b199407817036e3622ca7f06752c4ae0/.git # timeout=10 
Setting origin to https://github.com/odidev/apm-pipeline-library 
 > /usr/bin/git config remote.origin.url https://github.com/odidev/apm-pipeline-library # timeout=10 
Fetching origin... 
Fetching upstream changes from origin 
 > /usr/bin/git --version # timeout=10 
 > git --version # 'git version 2.34.1' 
 > /usr/bin/git config --get remote.origin.url # timeout=10 
using GIT_ASKPASS to set credentials credentials for testing 
 > /usr/bin/git fetch --tags --force --progress -- origin +refs/heads/*:refs/remotes/origin/* # timeout=10 
 > /usr/bin/git rev-parse current^{commit} # timeout=10 
 > /usr/bin/git branch -a -v --no-abbrev --contains 8c9bd4a22a5d43480d745b40e236647736ca504d # timeout=10 
Selected match: dependabot/gradle/dot-ci/jobDSL/org.jenkins-ci.plugins-git-4.11.3 revision 8c9bd4a22a5d43480d745b40e236647736ca504d 
The recommended git tool is: /usr/bin/git 
using credential df4a32df-4aed-4113-a9df-e13515364217 
 > /usr/bin/git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/apmtest_mbp_main@libs/51713b1b092d429595642cb35ca6b68eb12f5b87c96f27950bfb9b725e980690/.git # timeout=10 
Fetching changes from the remote Git repository 
 > /usr/bin/git config remote.origin.url https://github.com/odidev/apm-pipeline-library # timeout=10 
Fetching without tags 
Fetching upstream changes from https://github.com/odidev/apm-pipeline-library 
 > /usr/bin/git --version # timeout=10 
 > git --version # 'git version 2.34.1' 
using GIT_ASKPASS to set credentials credentials for testing 
 > /usr/bin/git fetch --no-tags --force --progress -- https://github.com/odidev/apm-pipeline-library +refs/heads/*:refs/remotes/origin/* # timeout=10 
Checking out Revision 8c9bd4a22a5d43480d745b40e236647736ca504d (dependabot/gradle/dot-ci/jobDSL/org.jenkins-ci.plugins-git-4.11.3) 
 > /usr/bin/git config core.sparsecheckout # timeout=10 
 > /usr/bin/git checkout -f 8c9bd4a22a5d43480d745b40e236647736ca504d # timeout=10 
Commit message: "docs: update CHANGELOG.md" 
 > /usr/bin/git rev-list --no-walk 8c9bd4a22a5d43480d745b40e236647736ca504d # timeout=10 
The recommended git tool is: /usr/bin/git 
using credential df4a32df-4aed-4113-a9df-e13515364217 
 > /usr/bin/git rev-parse HEAD^{commit} # timeout=10 
The recommended git tool is: /usr/bin/git 
using credential df4a32df-4aed-4113-a9df-e13515364217 
[GitCheckoutListener] Recording commits of 'git https://github.com/odidev/apm-pipeline-library' 
[GitCheckoutListener] Found previous build 'apmtest mbp/main #30' that contains recorded Git commits 
[GitCheckoutListener] -> Starting recording of new commits since '8c9bd4a' 
[GitCheckoutListener] -> Using head commit '8c9bd4a' as starting point 
[GitCheckoutListener] -> Git commit decorator successfully obtained 'hudson.plugins.git.browser.GithubWeb@26c7970d' to render commit links 
[GitCheckoutListener] -> No new commits found 
Excluding src/test/ from checkout of git https://github.com/odidev/apm-pipeline-library so that library test code cannot be accessed by Pipelines. 
To remove this log message, move the test code outside of src/. To restore the previous behavior that allowed access to files in src/test/, pass -Dorg.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.INCLUDE_SRC_TEST_IN_LIBRARIES=true to the java command used to start Jenkins. 
[Pipeline] Start of Pipeline 
[Pipeline] node 
Running on Jenkins in /var/lib/jenkins/workspace/apmtest_mbp_main 
[Pipeline] { 
[Pipeline] stage 
[Pipeline] { (Declarative: Checkout SCM) 
[Pipeline] echo 
[39;49m[INFO] Override default checkout[0m 
[Pipeline] retry 
[Pipeline] { 
[Pipeline] checkout 
The recommended git tool is: /usr/bin/git 
using credential df4a32df-4aed-4113-a9df-e13515364217 
 > /usr/bin/git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/apmtest_mbp_main/.git # timeout=10 
Fetching changes from the remote Git repository 
 > /usr/bin/git config remote.origin.url https://github.com/odidev/apm-integration-testing # timeout=10 
Fetching without tags 
Fetching upstream changes from https://github.com/odidev/apm-integration-testing 
 > /usr/bin/git --version # timeout=10 
 > git --version # 'git version 2.34.1' 
using GIT_ASKPASS to set credentials credentials for testing 
 > /usr/bin/git fetch --no-tags --force --progress -- https://github.com/odidev/apm-integration-testing +refs/heads/*:refs/remotes/origin/* # timeout=10 
Checking out Revision 62a77f0a03e00ecf0a6c45ec3268e1aeca2cdc80 (main) 
 > /usr/bin/git config core.sparsecheckout # timeout=10 
 > /usr/bin/git checkout -f 62a77f0a03e00ecf0a6c45ec3268e1aeca2cdc80 # timeout=10 
Commit message: "Update Jenkinsfile" 
 > /usr/bin/git rev-list --no-walk 309648ff4b8b36103ea0abe06056c501c02102b4 # timeout=10 
The recommended git tool is: /usr/bin/git 
using credential df4a32df-4aed-4113-a9df-e13515364217 
 > /usr/bin/git rev-parse HEAD^{commit} # timeout=10 
The recommended git tool is: /usr/bin/git 
using credential df4a32df-4aed-4113-a9df-e13515364217 
[GitCheckoutListener] Recording commits of 'git https://github.com/odidev/apm-integration-testing' 
[GitCheckoutListener] Found previous build 'apmtest mbp/main #30' that contains recorded Git commits 
[GitCheckoutListener] -> Starting recording of new commits since '309648f' 
[GitCheckoutListener] -> Using head commit '62a77f0' as starting point 
[GitCheckoutListener] -> Git commit decorator successfully obtained 'hudson.plugins.git.browser.GithubWeb@52a43f55' to render commit links 
[GitCheckoutListener] -> Recorded one new commit 
[Pipeline] } 
[Pipeline] // retry 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] withEnv 
[Pipeline] { 
[Pipeline] withEnv 
[Pipeline] { 
[Pipeline] timeout 
Timeout set to expire in 3 hr 0 min 
[Pipeline] { 
[Pipeline] timestamps 
[Pipeline] { 
[Pipeline] ansiColor 
[Pipeline] { 
18:39:52  
[Pipeline] stage 
[Pipeline] { (Checkout) 
[Pipeline] deleteDir 
[Pipeline] dir 
18:39:52 Running in /var/lib/jenkins/workspace/apmtest_mbp_main/https:/github.com/odidev/apm-integration-testing 
[Pipeline] { 
[Pipeline] echo 
18:39:52 [INFO] gitCheckout: Checkout SCM main with some customisation. 
[Pipeline] echo 
18:39:52 [INFO] Override default checkout 
[Pipeline] retry 
[Pipeline] { 
[Pipeline] checkout 
18:39:52 The recommended git tool is: /usr/bin/git 
18:39:52 using credential df4a32df-4aed-4113-a9df-e13515364217 
18:39:52 Cloning the remote Git repository 
18:39:52 Cloning repository https://github.com/odidev/apm-integration-testing 
18:39:52  > /usr/bin/git init /var/lib/jenkins/workspace/apmtest_mbp_main/https:/github.com/odidev/apm-integration-testing # timeout=10 
18:39:52 [WARNING] Reference path does not exist: /var/lib/jenkins/.git-references/apm-integration-testing.git 
18:39:52 Fetching upstream changes from https://github.com/odidev/apm-integration-testing 
18:39:52  > /usr/bin/git --version # timeout=10 
18:39:52  > git --version # 'git version 2.34.1' 
18:39:52 using GIT_ASKPASS to set credentials credentials for testing 
18:39:52  > /usr/bin/git fetch --tags --force --progress -- https://github.com/odidev/apm-integration-testing +refs/heads/*:refs/remotes/origin/* # timeout=10 
18:39:53  > /usr/bin/git config remote.origin.url https://github.com/odidev/apm-integration-testing # timeout=10 
18:39:53  > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10 
18:39:53 Avoid second fetch 
18:39:53  > /usr/bin/git rev-parse origin/main^{commit} # timeout=10 
18:39:53 Checking out Revision 62a77f0a03e00ecf0a6c45ec3268e1aeca2cdc80 (origin/main) 
18:39:53  > /usr/bin/git config core.sparsecheckout # timeout=10 
18:39:53  > /usr/bin/git checkout -f 62a77f0a03e00ecf0a6c45ec3268e1aeca2cdc80 # timeout=10 
18:39:53 Commit message: "Update Jenkinsfile" 
18:39:53 [GitCheckoutListener] Skipping recording, since SCM 'git https://github.com/odidev/apm-integration-testing' already has been processed 
[Pipeline] } 
[Pipeline] // retry 
[Pipeline] isUnix 
[Pipeline] withCredentials 
[Pipeline] // withCredentials 
[Pipeline] } 
[Pipeline] // dir 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] stage 
[Pipeline] { (pwd) 
Stage "pwd" skipped due to earlier failure(s) 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] stage 
[Pipeline] { (Lint) 
Stage "Lint" skipped due to earlier failure(s) 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] stage 
[Pipeline] { (Tests) 
Stage "Tests" skipped due to earlier failure(s) 
[Pipeline] parallel 
[Pipeline] { (Branch: Unit Tests) 
[Pipeline] { (Branch: Sanity checks) 
[Pipeline] stage 
[Pipeline] { (Unit Tests) 
[Pipeline] stage 
[Pipeline] { (Sanity checks) 
Stage "Unit Tests" skipped due to earlier failure(s) 
[Pipeline] } 
Stage "Sanity checks" skipped due to earlier failure(s) 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] // stage 
[Pipeline] } 
18:39:53 Failed in branch Unit Tests 
[Pipeline] } 
18:39:53 Failed in branch Sanity checks 
[Pipeline] // parallel 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] stage 
[Pipeline] { (Integration Tests) 
Stage "Integration Tests" skipped due to earlier failure(s) 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] stage 
[Pipeline] { (Declarative: Post Actions) 
[Pipeline] node 
18:39:53 Running on Jenkins in /var/lib/jenkins/workspace/apmtest_mbp_main@2 
[Pipeline] { 
[Pipeline] stage 
[Pipeline] { (Reporting build status) 
[Pipeline] echo 
18:39:53 [INFO] getVaultSecret: Getting secrets 
[Pipeline] withCredentials 
[Pipeline] // withCredentials 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] } 
[Pipeline] // node 
Error when executing cleanup post condition: 
org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: Could not find credentials entry with ID 'vault-addr' 
	at org.jenkinsci.plugins.credentialsbinding.MultiBinding.getCredentials(MultiBinding.java:197) 
	at org.jenkinsci.plugins.credentialsbinding.impl.StringBinding.bindSingle(StringBinding.java:57) 
	at org.jenkinsci.plugins.credentialsbinding.Binding.bind(Binding.java:149) 
	at org.jenkinsci.plugins.credentialsbinding.impl.BindingStep$Execution2.doStart(BindingStep.java:132) 
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77) 
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) 
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
	at java.base/java.lang.Thread.run(Thread.java:829) 
 
[Pipeline] } 
[Pipeline] // stage 
[Pipeline] } 
18:39:54  
[Pipeline] // ansiColor 
[Pipeline] } 
[Pipeline] // timestamps 
[Pipeline] } 
[Pipeline] // timeout 
[Pipeline] } 
[Pipeline] // withEnv 
[Pipeline] } 
[Pipeline] // withEnv 
[Pipeline] } 
[Pipeline] // node 
[Pipeline] End of Pipeline 
ERROR: Could not find credentials entry with ID '2a9602aa-ab9f-4e52-baf3-b71ca88469c7-UserAndToken' 
Finished: FAILURE 
``` 

Could you please have a look and share your suggestion on the same?

**Comment by v1v** [comment]
> org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: Could not find credentials entry with ID 'vault-addr' 

I guess, you are using your own Jenkins controller, if so, it won't work in your end, since it's not configured with the existing toolchain/credentials

If you follow the steps explained in https://github.com/elastic/apm-integration-testing/issues/1503#issuecomment-1187729835, does it work?

**Comment by odidev** [comment]
> If you follow the steps explained in [#1503 (comment)](https://github.com/elastic/apm-integration-testing/issues/1503#issuecomment-1187729835), does it work?

I tried running the script `.ci/script/all.sh` on Ubuntu Arm64 machine. While building the containers, wait-service container is giving the following error:  

``` 
ERROR: for wait-service  Container "49af1ccc1d2e" is unhealthy. 
ERROR: Encountered errors while bringing up the project. 
Traceback (most recent call last): 
  File "scripts/compose.py", line 31, in <module> 
    main() 
  File "scripts/compose.py", line 17, in main 
    setup() 
  File "/home/apm-integration-testing/scripts/modules/cli.py", line 214, in __call__ 
    self.args.func() 
  File "/home/apm-integration-testing/scripts/modules/cli.py", line 591, in start_handler 
    self.build_start_handler("start") 
  File "/home/apm-integration-testing/scripts/modules/cli.py", line 783, in build_start_handler 
    self.run_docker_compose_process(docker_compose_cmd + up_params) 
  File "/home/apm-integration-testing/scripts/modules/cli.py", line 477, in run_docker_compose_process 
    subprocess.check_call(docker_compose_cmd) 
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call 
    raise CalledProcessError(retcode, cmd) 
subprocess.CalledProcessError: Command '['docker-compose', '-f', '/home/apm-integration-testing/docker-compose.yml', 'up', '-d']' returned non-zero exit status 1. 
``` 
Also, I tried creating a container with `busybox` image as the wait-service container seems to be building one with the same and that container seems to be working fine. 
 

Could you please have a look and share your suggestion on the same?

**Comment by odidev** [comment]
Hi @v1v, Could you please have a look at this and share your suggestion?

**Comment by kuisathaverat** [comment]
>ERROR: for wait-service  Container "49af1ccc1d2e" is unhealthy. 

The containers are built. The error is related to one container with ID `49af1ccc1d2e`. `.ci/script/all.sh` run the Elastic Stack and all the Opbeans. To run this scenario, the host has to have Docker configured to use at least 8GB and 2 CPUs. To see the real issue the command `docker logs 49af1ccc1d2e` will give you the log output of the failed container, and `docker inspect 49af1ccc1d2e` will give you the reason why the container was stopped.

**Comment by odidev** [comment]
Thanks @kuisathaverat, wait service issue is resolved now.  

Currently I’m getting the following test failure on Ubuntu Arm64: 
``` 
tests/agent/test_rum.py::test_rum FAILED 
tests/server/test_transaction.py::test_process_transaction PASSED 
Using on memory OpenTelemetry exporter 

Number of spans: 256 

=================================== FAILURES =================================== 
___________________________________ test_rum ___________________________________  

rum = <tests.fixtures.agents.Agent object at 0xffff7c2a51d0> 

    def test_rum(rum): 
        elasticsearch = rum.apm_server.elasticsearch 
        elasticsearch.clean() 
        endpoint = Endpoint(rum.url, "run_integration_test", qu_str="echo=done", text="done") 
        r = requests.get(endpoint.url) 
>       utils.check_request_response(r, endpoint) 
tests/agent/test_rum.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

req = <Response [500]>
endpoint = <tests.endpoint.Endpoint object at 0xffff7c3ad950> 
    def check_request_response(req, endpoint): 
        msg = "Expected {}, got {}".format(endpoint.text, req.text) 
>       assert req.text.strip() == endpoint.text, msg 

E       AssertionError: Expected done, got Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT 
E 
E 
E       TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md 

tests/utils.py:43: AssertionError 
``` 

I checked the path `/usr/bin/chromium-browser` and chromium-browser is present there. Also, I checked the [troubleshooting.md file](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) and upgraded the node version as suggested there. 

 

Could you please have a look at this and share your suggestion on the same?

**Comment by v1v** [comment]
Hey @odidev , https://github.com/elastic/apm-integration-testing/pull/1524 removed all the tests in this project, thanks for investigating how to run on ARM64, much appreciated 🙏 

If no other concerns, I'd say we can close this issue

**Comment by odidev** [comment]
@v1v, I have successfully tested unit tests by running the script `.ci/scripts/unit-tests.sh` on ARM64 after removing '-XX:UseAVX=2' from `ES_JAVA_OPTS` present [here](https://github.com/elastic/apm-integration-testing/blob/main/scripts/tests/config/test_start_main_default.yml#L101). 

Are you interested in adding ARM64 job in CI for unit tests? If required, I am happy to contribute.
