### ISSUE TITLE
Filebeat throwing errors around custom formatting

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-integration-testing#280]
When running `master` with `--with-filebeat` to get logs into i.e. the Logs UI, I seem to be getting a bunch of errors that `Field [@timestamp] of type [keyword] does not support custom formats`

Here's the entire log output from Kibana;

```
[illegal_argument_exception] Field [@timestamp] of type [keyword] does not support custom formats (and) [illegal_argument_exception] Field [@timestamp] of type [keyword] does not support custom formats (and) [illegal_argument_exception] Field [@timestamp] of type [keyword] does not support custom formats (and) [illegal_argument_exception] Field [@timestamp] of type [keyword] does not support custom formats (and) [illegal_argument_exception] Field [@timestamp] of type [keyword] does not support custom formats :: {"path":"/filebeat-*/_search","query":{"allow_no_indices":true,"ignore_unavailable":true,"ignore_throttled":true},"body":"{\"aggregations\":{\"count_by_date\":{\"date_range\":{\"field\":\"@timestamp\",\"format\":\"epoch_millis\",\"ranges\":[{\"from\":1548504000000,\"to\":1548504864000},{\"from\":1548504864000,\"to\":1548505728000},{\"from\":1548505728000,\"to\":1548506592000},{\"from\":1548506592000,\"to\":1548507456000},{\"from\":1548507456000,\"to\":1548508320000},{\"from\":1548508320000,\"to\":1548509184000},{\"from\":1548509184000,\"to\":1548510048000},{\"from\":1548510048000,\"to\":1548510912000},{\"from\":1548510912000,\"to\":1548511776000},{\"from\":1548511776000,\"to\":1548512640000},{\"from\":1548512640000,\"to\":1548513504000},{\"from\":1548513504000,\"to\":1548514368000},{\"from\":1548514368000,\"to\":1548515232000},{\"from\":1548515232000,\"to\":1548516096000},{\"from\":1548516096000,\"to\":1548516960000},{\"from\":1548516960000,\"to\":1548517824000},{\"from\":1548517824000,\"to\":1548518688000},{\"from\":1548518688000,\"to\":1548519552000},{\"from\":1548519552000,\"to\":1548520416000},{\"from\":1548520416000,\"to\":1548521280000},{\"from\":1548521280000,\"to\":1548522144000},{\"from\":1548522144000,\"to\":1548523008000},{\"from\":1548523008000,\"to\":1548523872000},{\"from\":1548523872000,\"to\":1548524736000},{\"from\":1548524736000,\"to\":1548525600000},{\"from\":1548525600000,\"to\":1548526464000},{\"from\":1548526464000,\"to\":1548527328000},{\"from\":1548527328000,\"to\":1548528192000},{\"from\":1548528192000,\"to\":1548529056000},{\"from\":1548529056000,\"to\":1548529920000},{\"from\":1548529920000,\"to\":1548530784000},{\"from\":1548530784000,\"to\":1548531648000},{\"from\":1548531648000,\"to\":1548532512000},{\"from\":1548532512000,\"to\":1548533376000},{\"from\":1548533376000,\"to\":1548534240000},{\"from\":1548534240000,\"to\":1548535104000},{\"from\":1548535104000,\"to\":1548535968000},{\"from\":1548535968000,\"to\":1548536832000},{\"from\":1548536832000,\"to\":1548537696000},{\"from\":1548537696000,\"to\":1548538560000},{\"from\":1548538560000,\"to\":1548539424000},{\"from\":1548539424000,\"to\":1548540288000},{\"from\":1548540288000,\"to\":1548541152000},{\"from\":1548541152000,\"to\":1548542016000},{\"from\":1548542016000,\"to\":1548542880000},{\"from\":1548542880000,\"to\":1548543744000},{\"from\":1548543744000,\"to\":1548544608000},{\"from\":1548544608000,\"to\":1548545472000},{\"from\":1548545472000,\"to\":1548546336000},{\"from\":1548546336000,\"to\":1548547200000},{\"from\":1548547200000,\"to\":1548548064000},{\"from\":1548548064000,\"to\":1548548928000},{\"from\":1548548928000,\"to\":1548549792000},{\"from\":1548549792000,\"to\":1548550656000},{\"from\":1548550656000,\"to\":1548551520000},{\"from\":1548551520000,\"to\":1548552384000},{\"from\":1548552384000,\"to\":1548553248000},{\"from\":1548553248000,\"to\":1548554112000},{\"from\":1548554112000,\"to\":1548554976000},{\"from\":1548554976000,\"to\":1548555840000},{\"from\":1548555840000,\"to\":1548556704000},{\"from\":1548556704000,\"to\":1548557568000},{\"from\":1548557568000,\"to\":1548558432000},{\"from\":1548558432000,\"to\":1548559296000},{\"from\":1548559296000,\"to\":1548560160000},{\"from\":1548560160000,\"to\":1548561024000},{\"from\":1548561024000,\"to\":1548561888000},{\"from\":1548561888000,\"to\":1548562752000},{\"from\":1548562752000,\"to\":1548563616000},{\"from\":1548563616000,\"to\":1548564480000},{\"from\":1548564480000,\"to\":1548565344000},{\"from\":1548565344000,\"to\":1548566208000},{\"from\":1548566208000,\"to\":1548567072000},{\"from\":1548567072000,\"to\":1548567936000},{\"from\":1548567936000,\"to\":1548568800000},{\"from\":1548568800000,\"to\":1548569664000},{\"from\":1548569664000,\"to\":1548570528000},{\"from\":1548570528000,\"to\":1548571392000},{\"from\":1548571392000,\"to\":1548572256000},{\"from\":1548572256000,\"to\":1548573120000},{\"from\":1548573120000,\"to\":1548573984000},{\"from\":1548573984000,\"to\":1548574848000},{\"from\":1548574848000,\"to\":1548575712000},{\"from\":1548575712000,\"to\":1548576576000},{\"from\":1548576576000,\"to\":1548577440000},{\"from\":1548577440000,\"to\":1548578304000},{\"from\":1548578304000,\"to\":1548579168000},{\"from\":1548579168000,\"to\":1548580032000},{\"from\":1548580032000,\"to\":1548580896000},{\"from\":1548580896000,\"to\":1548581760000},{\"from\":1548581760000,\"to\":1548582624000},{\"from\":1548582624000,\"to\":1548583488000},{\"from\":1548583488000,\"to\":1548584352000},{\"from\":1548584352000,\"to\":1548585216000},{\"from\":1548585216000,\"to\":1548586080000},{\"from\":1548586080000,\"to\":1548586944000},{\"from\":1548586944000,\"to\":1548587808000},{\"from\":1548587808000,\"to\":1548588672000},{\"from\":1548588672000,\"to\":1548589536000},{\"from\":1548589536000,\"to\":1548590400000},{\"from\":1548590400000,\"to\":1548591264000},{\"from\":1548591264000,\"to\":1548592128000},{\"from\":1548592128000,\"to\":1548592992000},{\"from\":1548592992000,\"to\":1548593856000},{\"from\":1548593856000,\"to\":1548594720000},{\"from\":1548594720000,\"to\":1548595584000},{\"from\":1548595584000,\"to\":1548596448000},{\"from\":1548596448000,\"to\":1548597312000},{\"from\":1548597312000,\"to\":1548598176000},{\"from\":1548598176000,\"to\":1548599040000},{\"from\":1548599040000,\"to\":1548599904000},{\"from\":1548599904000,\"to\":1548600768000},{\"from\":1548600768000,\"to\":1548601632000},{\"from\":1548601632000,\"to\":1548602496000},{\"from\":1548602496000,\"to\":1548603360000},{\"from\":1548603360000,\"to\":1548604224000},{\"from\":1548604224000,\"to\":1548605088000},{\"from\":1548605088000,\"to\":1548605952000},{\"from\":1548605952000,\"to\":1548606816000},{\"from\":1548606816000,\"to\":1548607680000},{\"from\":1548607680000,\"to\":1548608544000},{\"from\":1548608544000,\"to\":1548609408000},{\"from\":1548609408000,\"to\":1548610272000},{\"from\":1548610272000,\"to\":1548611136000},{\"from\":1548611136000,\"to\":1548612000000},{\"from\":1548612000000,\"to\":1548612864000},{\"from\":1548612864000,\"to\":1548613728000},{\"from\":1548613728000,\"to\":1548614592000},{\"from\":1548614592000,\"to\":1548615456000},{\"from\":1548615456000,\"to\":1548616320000},{\"from\":1548616320000,\"to\":1548617184000},{\"from\":1548617184000,\"to\":1548618048000},{\"from\":1548618048000,\"to\":1548618912000},{\"from\":1548618912000,\"to\":1548619776000},{\"from\":1548619776000,\"to\":1548620640000},{\"from\":1548620640000,\"to\":1548621504000},{\"from\":1548621504000,\"to\":1548622368000},{\"from\":1548622368000,\"to\":1548623232000},{\"from\":1548623232000,\"to\":1548624096000},{\"from\":1548624096000,\"to\":1548624960000},{\"from\":1548624960000,\"to\":1548625824000},{\"from\":1548625824000,\"to\":1548626688000},{\"from\":1548626688000,\"to\":1548627552000},{\"from\":1548627552000,\"to\":1548628416000},{\"from\":1548628416000,\"to\":1548629280000},{\"from\":1548629280000,\"to\":1548630144000},{\"from\":1548630144000,\"to\":1548631008000},{\"from\":1548631008000,\"to\":1548631872000},{\"from\":1548631872000,\"to\":1548632736000},{\"from\":1548632736000,\"to\":1548633600000},{\"from\":1548633600000,\"to\":1548634464000},{\"from\":1548634464000,\"to\":1548635328000},{\"from\":1548635328000,\"to\":1548636192000},{\"from\":1548636192000,\"to\":1548637056000},{\"from\":1548637056000,\"to\":1548637920000},{\"from\":1548637920000,\"to\":1548638784000},{\"from\":1548638784000,\"to\":1548639648000},{\"from\":1548639648000,\"to\":1548640512000},{\"from\":1548640512000,\"to\":1548641376000},{\"from\":1548641376000,\"to\":1548642240000},{\"from\":1548642240000,\"to\":1548643104000},{\"from\":1548643104000,\"to\":1548643968000},{\"from\":1548643968000,\"to\":1548644832000},{\"from\":1548644832000,\"to\":1548645696000},{\"from\":1548645696000,\"to\":1548646560000},{\"from\":1548646560000,\"to\":1548647424000},{\"from\":1548647424000,\"to\":1548648288000},{\"from\":1548648288000,\"to\":1548649152000},{\"from\":1548649152000,\"to\":1548650016000},{\"from\":1548650016000,\"to\":1548650880000},{\"from\":1548650880000,\"to\":1548651744000},{\"from\":1548651744000,\"to\":1548652608000},{\"from\":1548652608000,\"to\":1548653472000},{\"from\":1548653472000,\"to\":1548654336000},{\"from\":1548654336000,\"to\":1548655200000},{\"from\":1548655200000,\"to\":1548656064000},{\"from\":1548656064000,\"to\":1548656928000},{\"from\":1548656928000,\"to\":1548657792000},{\"from\":1548657792000,\"to\":1548658656000},{\"from\":1548658656000,\"to\":1548659520000},{\"from\":1548659520000,\"to\":1548660384000},{\"from\":1548660384000,\"to\":1548661248000},{\"from\":1548661248000,\"to\":1548662112000},{\"from\":1548662112000,\"to\":1548662976000},{\"from\":1548662976000,\"to\":1548663840000},{\"from\":1548663840000,\"to\":1548664704000},{\"from\":1548664704000,\"to\":1548665568000},{\"from\":1548665568000,\"to\":1548666432000},{\"from\":1548666432000,\"to\":1548667296000},{\"from\":1548667296000,\"to\":1548668160000},{\"from\":1548668160000,\"to\":1548669024000},{\"from\":1548669024000,\"to\":1548669888000},{\"from\":1548669888000,\"to\":1548670752000},{\"from\":1548670752000,\"to\":1548671616000},{\"from\":1548671616000,\"to\":1548672480000},{\"from\":1548672480000,\"to\":1548673344000},{\"from\":1548673344000,\"to\":1548674208000},{\"from\":1548674208000,\"to\":1548675072000},{\"from\":1548675072000,\"to\":1548675936000},{\"from\":1548675936000,\"to\":1548676800000},{\"from\":1548676800000,\"to\":1548677664000},{\"from\":1548677664000,\"to\":1548678528000},{\"from\":1548678528000,\"to\":1548679392000},{\"from\":1548679392000,\"to\":1548680256000},{\"from\":1548680256000,\"to\":1548681120000},{\"from\":1548681120000,\"to\":1548681984000},{\"from\":1548681984000,\"to\":1548682848000},{\"from\":1548682848000,\"to\":1548683712000},{\"from\":1548683712000,\"to\":1548684576000},{\"from\":1548684576000,\"to\":1548685440000},{\"from\":1548685440000,\"to\":1548686304000},{\"from\":1548686304000,\"to\":1548687168000},{\"from\":1548687168000,\"to\":1548688032000},{\"from\":1548688032000,\"to\":1548688896000},{\"from\":1548688896000,\"to\":1548689760000},{\"from\":1548689760000,\"to\":1548690624000},{\"from\":1548690624000,\"to\":1548691488000},{\"from\":1548691488000,\"to\":1548692352000},{\"from\":1548692352000,\"to\":1548693216000},{\"from\":1548693216000,\"to\":1548694080000},{\"from\":1548694080000,\"to\":1548694944000},{\"from\":1548694944000,\"to\":1548695808000},{\"from\":1548695808000,\"to\":1548696672000},{\"from\":1548696672000,\"to\":1548697536000},{\"from\":1548697536000,\"to\":1548698400000},{\"from\":1548698400000,\"to\":1548699264000},{\"from\":1548699264000,\"to\":1548700128000},{\"from\":1548700128000,\"to\":1548700992000},{\"from\":1548700992000,\"to\":1548701856000},{\"from\":1548701856000,\"to\":1548702720000},{\"from\":1548702720000,\"to\":1548703584000},{\"from\":1548703584000,\"to\":1548704448000},{\"from\":1548704448000,\"to\":1548705312000},{\"from\":1548705312000,\"to\":1548706176000},{\"from\":1548706176000,\"to\":1548707040000},{\"from\":1548707040000,\"to\":1548707904000},{\"from\":1548707904000,\"to\":1548708768000},{\"from\":1548708768000,\"to\":1548709632000},{\"from\":1548709632000,\"to\":1548710496000},{\"from\":1548710496000,\"to\":1548711360000},{\"from\":1548711360000,\"to\":1548712224000},{\"from\":1548712224000,\"to\":1548713088000},{\"from\":1548713088000,\"to\":1548713952000},{\"from\":1548713952000,\"to\":1548714816000},{\"from\":1548714816000,\"to\":1548715680000},{\"from\":1548715680000,\"to\":1548716544000},{\"from\":1548716544000,\"to\":1548717408000},{\"from\":1548717408000,\"to\":1548718272000},{\"from\":1548718272000,\"to\":1548719136000},{\"from\":1548719136000,\"to\":1548720000000},{\"from\":1548720000000,\"to\":1548720864000},{\"from\":1548720864000,\"to\":1548721728000},{\"from\":1548721728000,\"to\":1548722592000},{\"from\":1548722592000,\"to\":1548723456000},{\"from\":1548723456000,\"to\":1548724320000},{\"from\":1548724320000,\"to\":1548725184000},{\"from\":1548725184000,\"to\":1548726048000},{\"from\":1548726048000,\"to\":1548726912000},{\"from\":1548726912000,\"to\":1548727776000},{\"from\":1548727776000,\"to\":1548728640000},{\"from\":1548728640000,\"to\":1548729504000},{\"from\":1548729504000,\"to\":1548730368000},{\"from\":1548730368000,\"to\":1548731232000},{\"from\":1548731232000,\"to\":1548732096000},{\"from\":1548732096000,\"to\":1548732960000},{\"from\":1548732960000,\"to\":1548733824000},{\"from\":1548733824000,\"to\":1548734688000},{\"from\":1548734688000,\"to\":1548735552000},{\"from\":1548735552000,\"to\":1548736416000},{\"from\":1548736416000,\"to\":1548737280000},{\"from\":1548737280000,\"to\":1548738144000},{\"from\":1548738144000,\"to\":1548739008000},{\"from\":1548739008000,\"to\":1548739872000},{\"from\":1548739872000,\"to\":1548740736000},{\"from\":1548740736000,\"to\":1548741600000},{\"from\":1548741600000,\"to\":1548742464000},{\"from\":1548742464000,\"to\":1548743328000},{\"from\":1548743328000,\"to\":1548744192000},{\"from\":1548744192000,\"to\":1548745056000},{\"from\":1548745056000,\"to\":1548745920000},{\"from\":1548745920000,\"to\":1548746784000},{\"from\":1548746784000,\"to\":1548747648000},{\"from\":1548747648000,\"to\":1548748512000},{\"from\":1548748512000,\"to\":1548749376000},{\"from\":1548749376000,\"to\":1548750240000},{\"from\":1548750240000,\"to\":1548751104000},{\"from\":1548751104000,\"to\":1548751968000},{\"from\":1548751968000,\"to\":1548752832000},{\"from\":1548752832000,\"to\":1548753696000},{\"from\":1548753696000,\"to\":1548754560000},{\"from\":1548754560000,\"to\":1548755424000},{\"from\":1548755424000,\"to\":1548756288000},{\"from\":1548756288000,\"to\":1548757152000},{\"from\":1548757152000,\"to\":1548758016000},{\"from\":1548758016000,\"to\":1548758880000},{\"from\":1548758880000,\"to\":1548759744000},{\"from\":1548759744000,\"to\":1548760608000},{\"from\":1548760608000,\"to\":1548761472000},{\"from\":1548761472000,\"to\":1548762336000},{\"from\":1548762336000,\"to\":1548763200000}]}}},\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1548504000000,\"lte\":1548763200000,\"format\":\"epoch_millis\"}}}]}},\"size\":0}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"},{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"},{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"},{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"},{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"filebeat-7.0.0-2019.01.23\",\"node\":\"QuoPZdtmSb2IHMV0eYOZQg\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"}},{\"shard\":0,\"index\":\"filebeat-7.0.0-2019.01.24\",\"node\":\"QuoPZdtmSb2IHMV0eYOZQg\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"}},{\"shard\":0,\"index\":\"filebeat-7.0.0-2019.01.25\",\"node\":\"QuoPZdtmSb2IHMV0eYOZQg\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"}},{\"shard\":0,\"index\":\"filebeat-7.0.0-2019.01.29\",\"node\":\"QuoPZdtmSb2IHMV0eYOZQg\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"}},{\"shard\":0,\"index\":\"filebeat-7.0.0-2019.01.30\",\"node\":\"QuoPZdtmSb2IHMV0eYOZQg\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"}}],\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Field [@timestamp] of type [keyword] does not support custom formats\"}}},\"status\":400}"}
    at respond (/Users/casperhubertz/dev/elastic/kibana/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/Users/casperhubertz/dev/elastic/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/Users/casperhubertz/dev/elastic/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/Users/casperhubertz/dev/elastic/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
TypeError: Float cannot represent non numeric value: 2019-01-23T10:06:04.572Z
    at coerceFloat (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/type/scalars.js:69:9)
    at GraphQLScalarType.serialize (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/type/definition.js:418:12)
    at completeLeafValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:701:37)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:649:12)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:629:21)
    at completeValueWithLocatedError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:580:21)
    at completeValueCatchingError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:550:12)
    at resolveField (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:497:10)
    at /Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:772:10)
    at completeObjectValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:762:10)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:660:12)
    at completeValueWithLocatedError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:580:21)
    at completeValueCatchingError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:556:21)
    at resolveField (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:497:10)
    at /Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:772:10)
    at completeObjectValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:762:10)
TypeError: Float cannot represent non numeric value: 2019-01-23T10:37:51.223Z
    at coerceFloat (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/type/scalars.js:69:9)
    at GraphQLScalarType.serialize (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/type/definition.js:418:12)
    at completeLeafValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:701:37)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:649:12)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:629:21)
    at completeValueWithLocatedError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:580:21)
    at completeValueCatchingError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:550:12)
    at resolveField (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:497:10)
    at /Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:772:10)
    at completeObjectValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:762:10)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:660:12)
    at completeValueWithLocatedError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:580:21)
    at completeValueCatchingError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:556:21)
    at resolveField (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:497:10)
    at /Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:772:10)
    at completeObjectValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:762:10)
TypeError: Float cannot represent non numeric value: 2019-01-23T10:06:04.572Z
    at coerceFloat (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/type/scalars.js:69:9)
    at GraphQLScalarType.serialize (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/type/definition.js:418:12)
    at completeLeafValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:701:37)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:649:12)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:629:21)
    at completeValueWithLocatedError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:580:21)
    at completeValueCatchingError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:550:12)
    at resolveField (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:497:10)
    at /Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:772:10)
    at completeObjectValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:762:10)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:660:12)
    at completeValue (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:629:21)
    at completeValueWithLocatedError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:580:21)
    at completeValueCatchingError (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:550:12)
    at resolveField (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:497:10)
    at /Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/Users/casperhubertz/dev/elastic/kibana/node_modules/graphql/execution/execute.js:772:10)
```

All I'm seeing in Kibana is

<img width="1707" alt="screenshot 2019-01-30 at 13 57 13" src="https://user-images.githubusercontent.com/4104278/51982684-fd9b0480-2496-11e9-815d-58d6abde7b83.png">

**Comment by graphaelli** [comment]
Looks like this is working now, right @formgeist ?

**Comment by formgeist** [comment]
@graphaelli It might, I can't test it right now because Docker is refusing to build `master` properly. Getting this when trying to start;

```ERROR: for apm-server  Container "12b8ebaa8c88" is unhealthy.

ERROR: for filebeat  Container "12b8ebaa8c88" is unhealthy.```

I have removed all images and tried again, but no luck.

**Comment by formgeist** [comment]
Ok, got it up and running, and it works👍
