### ISSUE TITLE
[APM-CI][Integration test] RUM-js ITs are failing with some infra issues

### ISSUE THREAD

**Issue by v1v** [elastic/apm-integration-testing#427]
## What

```
09:05:39  Alpine users please run: `sudo apk add python make g++`
09:05:39  gyp ERR! configure error 
09:05:39  gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
09:05:39  gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
09:05:39  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
09:05:39  gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
09:05:39  gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
09:05:39  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
09:05:39  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
09:05:39  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
09:05:39  gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
09:05:39  gyp ERR! System Linux 4.15.0-1029-gcp
09:05:39  gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
09:05:39  gyp ERR! cwd /rumjs-integration-test/node_modules/fibers
09:05:39  gyp ERR! node -v v8.16.0
09:05:39  gyp ERR! node-gyp -v v3.8.0
09:05:39  gyp ERR! not ok 
09:05:39  node-gyp exited with code: 1
09:05:39  Please make sure you are using a supported platform and node version. If you
09:05:39  would like to compile fibers on this machine please make sure you have setup your
09:05:39  build environment--
09:05:39  Windows + OS X instructions here: https://github.com/nodejs/node-gyp
09:05:39  Ubuntu users please run: `sudo apt-get install g++ build-essential`
09:05:39  RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
09:05:39  Alpine users please run: `sudo apk add python make g++`
09:05:41  npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
09:05:41  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
09:05:41  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
09:05:41  
09:05:41  npm ERR! code ELIFECYCLE
09:05:41  npm ERR! errno 1
09:05:41  npm ERR! fibers@4.0.0 install: `node build.js || nodejs build.js`
09:05:41  npm ERR! Exit status 1
09:05:41  npm ERR! 
09:05:41  npm ERR! Failed at the fibers@4.0.0 install script.
09:05:41  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
09:05:41  
09:05:41  npm ERR! A complete log of this run can be found in:
09:05:41  npm ERR!     /root/.npm/_logs/2019-05-01T08_05_41_197Z-debug.log
09:05:42  Service 'agent-rumjs' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
09:05:42  Makefile:30: recipe for target 'start-env' failed
09:05:42  make[1]: *** [start-env] Error 1
09:05:42  make[1]: Leaving directory '/var/lib/jenkins/workspace/apm-integration-test-axis-pipeline/src/github.com/elastic/apm-integration-testing'
09:05:42  Makefile:41: recipe for target 'env-agent-rum' failed
09:05:42  make: *** [env-agent-rum] Error 2
```

## How 
- CI -> [here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-test-axis-pipeline/detail/apm-integration-test-axis-pipeline/3720/pipeline#step-59-log-358)
- Locally 
```
python scripts/compose.py start 7.0.0   --apm-server-build https://github.com/elastic/apm-server.git@master --rum-agent-branch='master' --no-apm-server-dashboards --no-apm-server-self-instrument --no-kibana --with-agent-rumjs --force-build
```

**Comment by v1v** [comment]
https://github.com/npm/cli/pull/86 has been fixed in `npm@6.9.0` although it seems the above refers when using `node8:slim` with `npm@latest`, the below log output refers to the local testing:

```
 ---> 557dfeb1c8c3
Step 10/19 : RUN npm install -g npm@latest
 ---> Running in e3598af1c284
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.9.0
added 54 packages from 9 contributors, removed 15 packages and updated 47 packages in 11.432s
Removing intermediate container e3598af1c284
 ---> b8e0d7cea811
Step 11/19 : RUN rm package-lock.json
 ---> Running in 977a27d18017
Removing intermediate container 977a27d18017
 ---> 747ec0843044
Step 12/19 : RUN npm install
 ---> Running in 667ba1a48dd9
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

> fibers@4.0.0 install /rumjs-integration-test/node_modules/fibers
> node build.js || nodejs build.js

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /rumjs-integration-test/node_modules/fibers
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /rumjs-integration-test/node_modules/fibers
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.0 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-01T10_01_21_566Z-debug.log
ERROR: Service 'agent-rumjs' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

If I remove the fixes introduced in:
- https://github.com/elastic/apm-integration-testing/pull/339
- https://github.com/elastic/apm-integration-testing/pull/347

Then everything works as expected:

```
Step 10/17 : RUN npm install
 ---> Running in 63031287d094

> fibers@3.1.1 install /rumjs-integration-test/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57-glibc` exists; testing
Binary is fine; exiting

> iltorb@1.3.10 install /rumjs-integration-test/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild


> wd@1.11.1 install /rumjs-integration-test/node_modules/wd
> node scripts/build-browser-scripts


> husky@1.3.1 install /rumjs-integration-test/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> puppeteer@1.13.0 install /rumjs-integration-test/node_modules/puppeteer
> node install.js


Chromium downloaded to /rumjs-integration-test/node_modules/puppeteer/.local-chromium/linux-637110

> sauce-connect-launcher@1.2.4 postinstall /rumjs-integration-test/node_modules/sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1692 packages from 1202 contributors and audited 58902 packages in 50.143s
found 57 vulnerabilities (2 low, 21 moderate, 34 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 63031287d094
 ---> 942451932cdc
Step 11/17 : RUN npx lerna run build && npx lerna run build:e2e
 ---> Running in 1906bd331b41
```

ITs then work like a charm:
```
TARGET=test-agent-rum make dockerized-test
...
tests/agent/test_rum.py::test_rum PASSED                                 [100%]

---------- generated xml file: /app/tests/results/agent-rum-junit.xml ----------
=========================== 1 passed in 4.11 seconds ===========================
```
