### ISSUE TITLE
Service 'agent-rumjs' failed to build

### ISSUE THREAD

**Issue by v1v** [elastic/apm-integration-testing#531]
```
19:52:29  Service 'agent-rumjs' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

```
19:52:26  > fibers@4.0.1 install /rumjs-integration-test/node_modules/fibers
19:52:26  > node build.js || nodejs build.js
19:52:26  
19:52:26  gyp ERR! configure error 
19:52:26  gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
19:52:26  gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
19:52:26  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
19:52:26  gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
19:52:26  gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
19:52:26  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
19:52:26  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
19:52:26  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
19:52:26  gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
19:52:26  gyp ERR! System Linux 4.15.0-1036-gcp
19:52:26  gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
19:52:26  gyp ERR! cwd /rumjs-integration-test/node_modules/fibers
19:52:26  gyp ERR! node -v v8.16.0
19:52:26  gyp ERR! node-gyp -v v3.8.0
19:52:26  gyp ERR! not ok 
19:52:26  node-gyp exited with code: 1
19:52:26  Please make sure you are using a supported platform and node version. If you
19:52:26  would like to compile fibers on this machine please make sure you have setup your
19:52:26  build environment--
19:52:26  Windows + OS X instructions here: https://github.com/nodejs/node-gyp
19:52:26  Ubuntu users please run: `sudo apt-get install g++ build-essential`
19:52:26  RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
19:52:26  Alpine users please run: `sudo apk add python make g++`
19:52:26  gyp ERR! configure error 
19:52:26  gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
19:52:26  gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
19:52:26  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
19:52:26  gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
19:52:26  gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
19:52:26  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
19:52:26  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
19:52:26  gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
19:52:26  gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
19:52:26  gyp ERR! System Linux 4.15.0-1036-gcp
19:52:26  gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
19:52:26  gyp ERR! cwd /rumjs-integration-test/node_modules/fibers
19:52:26  gyp ERR! node -v v8.16.0
19:52:26  gyp ERR! node-gyp -v v3.8.0
19:52:26  gyp ERR! not ok 
19:52:26  node-gyp exited with code: 1
19:52:26  Please make sure you are using a supported platform and node version. If you
19:52:26  would like to compile fibers on this machine please make sure you have setup your
19:52:26  build environment--
19:52:26  Windows + OS X instructions here: https://github.com/nodejs/node-gyp
19:52:26  Ubuntu users please run: `sudo apt-get install g++ build-essential`
19:52:26  RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
19:52:26  Alpine users please run: `sudo apk add python make g++`
19:52:28  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/@wdio/cli/node_modules/fsevents):
19:52:28  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
19:52:28  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
19:52:28  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
19:52:28  
19:52:28  npm ERR! code ELIFECYCLE
19:52:28  npm ERR! errno 1
19:52:28  npm ERR! fibers@4.0.1 install: `node build.js || nodejs build.js`
19:52:28  npm ERR! Exit status 1
19:52:28  npm ERR! 
19:52:28  npm ERR! Failed at the fibers@4.0.1 install script.
19:52:28  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:52:28  
19:52:28  npm ERR! A complete log of this run can be found in:
19:52:28  npm ERR!     /root/.npm/_logs/2019-07-09T18_52_28_514Z-debug.log
19:52:29  
19:52:29  ERROR: for agent-rumjs  (<Service: agent-rumjs>, "The command '/bin/sh -c npm install' returned a non-zero code: 1")
19:52:29  Service 'agent-rumjs' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

## How to reproduce locally?
- git clone https://github.com/elastic/apm-integration-testing
- run 
```
 python scripts/compose.py start 8.0.0   \
      --rum-agent-branch='master' \
      --no-apm-server-dashboards \
      --no-apm-server-self-instrument \
      --no-kibana \
      --with-agent-rumjs \
      --force-build
```

**Comment by v1v** [comment]
https://github.com/elastic/apm-integration-testing/blob/master/docker/rum/Dockerfile is the docker image used for building the rumjs app in the apm-integration-testing repo.

**Comment by v1v** [comment]
It seems this particular issue was after merging:
- https://github.com/elastic/apm-agent-rum-js/pull/312
