### ISSUE TITLE
Opbeans node is broken after Docker images changes

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#659]
After lates changes on Opbeans-node Docker image, the Docker image in the integration testing is broken

`./scripts/compose.py start 7.4.0 --release --with-opbeans-node`

```
2019-10-29T11:04:59: PM2 log: Launching in no daemon mode
2019-10-29T11:04:59: PM2 log: App [server:0] starting in -cluster mode-
2019-10-29T11:04:59: PM2 log: App [workload:1] starting in -cluster mode-
2019-10-29T11:04:59: PM2 log: App [workload:1] online
2019-10-29T11:04:59: PM2 log: App [server:0] online
/app/.workload.js
Sending error to Elastic APM { id: '5b75e9b2ee1b4a8588134e270a10aeb0' }
2019-10-29T11:05:01: PM2 log: App name:workload id:1 disconnected
2019-10-29T11:05:01: PM2 log: App [workload:1] exited with code [1] via signal [SIGINT]
{"level":30,"time":1572347101967,"pid":19,"hostname":"6879da2b4a34","msg":"server is listening on port 3000","v":1}
2019-10-29T11:05:03: PM2 log: App [workload:1] starting in -cluster mode-
2019-10-29T11:05:03: PM2 log: App [workload:1] online
/app/.workload.js
{"level":20,"time":1572347105480,"pid":19,"hostname":"6879da2b4a34","req":{"id":1,"method":"GET","url":"/throw-async-error","headers":{"user-agent":"workload/2.
4.3","host":"opbeans-node:3000","connection":"close"},"remoteAddress":"::ffff:172.20.0.7","remotePort":35658},"msg":"request received","v":1}
{"level":30,"time":1572347105509,"pid":19,"hostname":"6879da2b4a34","msg":"Sending error to Elastic APM {\"id\":\"6d3471552be164764679f35d81771283\"}","v":1}
{"level":50,"time":1572347105504,"pid":19,"hostname":"6879da2b4a34","msg":"this will not get captured by express","stack":"Error: this will not get captured by 
express\n    at /app/server/coffee.js:42:11\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickCallback (internal/process/
next_tick.js:181:9)","type":"Error","v":1}
{"level":50,"time":1572347105504,"pid":19,"hostname":"6879da2b4a34","msg":"Application encountered an uncaught exception. Flushing Elastic APM queue and exiting
...","v":1}
{"level":50,"time":1572347105506,"pid":19,"hostname":"6879da2b4a34","msg":"Elastic APM queue flushed!","v":1}
2019-10-29T11:05:05: PM2 log: App name:server id:0 disconnected
2019-10-29T11:05:05: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
2019-10-29T11:05:05: PM2 log: App [server:0] starting in -cluster mode-
Sending error to Elastic APM { id: 'b61b466a0c36ab38037887d878fd6cfe' }
2019-10-29T11:05:05: PM2 log: App name:workload id:1 disconnected
2019-10-29T11:05:05: PM2 log: App [workload:1] exited with code [1] via signal [SIGINT]
2019-10-29T11:05:05: PM2 log: App [server:0] online
{"level":30,"time":1572347106930,"pid":51,"hostname":"6879da2b4a34","msg":"server is listening on port 3000","v":1}
2019-10-29T11:05:07: PM2 log: App [workload:1] starting in -cluster mode-
2019-10-29T11:05:07: PM2 log: App [workload:1] online
{"level":20,"time":1572347107828,"pid":51,"hostname":"6879da2b4a34","req":{"id":1,"method":"GET","url":"/","headers":{"host":"opbeans-node:3000","user-agent":"W
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Error: connect ECONNREFUSED 172.20.0.7:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
T http://opbeans-node:3000/api/products/2/customers
{"level":30,"time":1572347109390,"pid":51,"hostname":"6879da2b4a34","req":{"id":2,"method":"GET","url":"/api/products/2/customers","headers":{"user-agent":"workload/2.4.3","host":"opbeans-node:3000","connection":"close"},"remoteAddress":"::ffff:172.20.0.7","remotePort":35682},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"21284","etag":"W/\"5324-NP5pUxBZCR7v9As8GdbIdG4jqPc\""}},"responseTime":157,"msg":"request completed","v":1}
{"level":20,"time":1572347109732,"pid":51,"hostname":"6879da2b4a34","req":{"id":3,"method":"GET","url":"/api/stats","headers":{"user-agent":"workload/2.4.3","host":"opbeans-node:3000","connection":"close"},"remoteAddress":"::ffff:172.20.0.7","remotePort":35686},"msg":"request received","v":1}
:Error: connect ECONNREFUSED 172.20.0.7:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Error: connect ECONNREFUSED 172.20.0.7:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

```

**Comment by kuisathaverat** [comment]
it is a random error so I guess it is related to the node-8-alpine image

**Comment by kuisathaverat** [comment]
PR related https://github.com/elastic/opbeans-node/pull/64
