### ISSUE TITLE
Identify the root cause of the Python issues

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#685]
since 2 weeks the Python tests on the master branch are failing, it does not happen locally so it is something related to the CI.

**Comment by kuisathaverat** [comment]
I was looking for errors on the integration test and I did not realize that Python containers have errors before start

```
[2019-12-09T18:36:17.339Z] ***********************************************************
[2019-12-09T18:36:17.339Z] ***************Docker Container 528b31c28df5***************
[2019-12-09T18:36:17.339Z] ***********************************************************
[2019-12-09T18:36:17.339Z] CONTAINER ID                                                       IMAGE                                         COMMAND                                                                                             CREATED             STATUS                    PORTS                      NAMES
[2019-12-09T18:36:17.339Z] 528b31c28df5f9b4476806daa2077dad8478b7c91e3dd816aa5351a35372407a   apm-integration-testing_agent-python-django   "bash -c 'pip install -q -U elastic-apm==5.1 && python testapp/manage.py runserver 0.0.0.0:8003'"   15 seconds ago      Up 11 seconds (healthy)   127.0.0.1:8003->8003/tcp   djangoapp
[2019-12-09T18:36:17.339Z] ----
[2019-12-09T18:36:17.339Z] Exception in thread eapm conf updater:
[2019-12-09T18:36:17.339Z] Traceback (most recent call last):
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2019-12-09T18:36:17.339Z]     self.run()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/utils/threading.py", line 79, in run
[2019-12-09T18:36:17.340Z]     rval = self._function(*self._args, **self._kwargs)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/conf/__init__.py", line 402, in update_config
[2019-12-09T18:36:17.340Z]     new_version, new_config, next_run = transport.get_config(agent.config.config_version, keys)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/transport/http.py", line 116, in get_config
[2019-12-09T18:36:17.340Z]     response = self.http.urlopen(
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
[2019-12-09T18:36:17.340Z]     response = conn.urlopen(method, u.request_uri, **kw)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
[2019-12-09T18:36:17.340Z]     return wrapped(*args, **kwargs)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 654, in urlopen
[2019-12-09T18:36:17.340Z]     conn = self._get_conn(timeout=pool_timeout)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
[2019-12-09T18:36:17.340Z]     return conn or self._new_conn()
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 228, in _new_conn
[2019-12-09T18:36:17.340Z]     conn = self.ConnectionCls(
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 112, in __init__
[2019-12-09T18:36:17.340Z]     _HTTPConnection.__init__(self, *args, **kw)
[2019-12-09T18:36:17.340Z] TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
[2019-12-09T18:36:17.340Z] Exception in thread eapm conf updater:
[2019-12-09T18:36:17.340Z] Traceback (most recent call last):
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2019-12-09T18:36:17.340Z]     self.run()
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/utils/threading.py", line 79, in run
[2019-12-09T18:36:17.340Z]     rval = self._function(*self._args, **self._kwargs)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/conf/__init__.py", line 402, in update_config
[2019-12-09T18:36:17.340Z]     new_version, new_config, next_run = transport.get_config(agent.config.config_version, keys)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/transport/http.py", line 116, in get_config
[2019-12-09T18:36:17.340Z]     response = self.http.urlopen(
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
[2019-12-09T18:36:17.340Z]     response = conn.urlopen(method, u.request_uri, **kw)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
[2019-12-09T18:36:17.340Z]     return wrapped(*args, **kwargs)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 654, in urlopen
[2019-12-09T18:36:17.340Z]     conn = self._get_conn(timeout=pool_timeout)
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
[2019-12-09T18:36:17.340Z]     return conn or self._new_conn()
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 228, in _new_conn
[2019-12-09T18:36:17.340Z]     conn = self.ConnectionCls(
[2019-12-09T18:36:17.340Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 112, in __init__
[2019-12-09T18:36:17.340Z]     _HTTPConnection.__init__(self, *args, **kw)
[2019-12-09T18:36:17.340Z] TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
```

```
[2019-12-09T18:36:17.071Z] ***********************************************************
[2019-12-09T18:36:17.071Z] ***************Docker Container 58e9ad07bf81***************
[2019-12-09T18:36:17.071Z] ***********************************************************
[2019-12-09T18:36:17.071Z] CONTAINER ID                                                       IMAGE                                        COMMAND                                                              CREATED             STATUS                    PORTS                      NAMES
[2019-12-09T18:36:17.071Z] 58e9ad07bf81c63f261f5d24915b78a7a565d05d594c5d52d0212d74df2876dc   apm-integration-testing_agent-python-flask   "bash -c 'pip install -q -U elastic-apm==5.1 && gunicorn app:app'"   15 seconds ago      Up 12 seconds (healthy)   127.0.0.1:8001->8001/tcp   flaskapp
[2019-12-09T18:36:17.071Z] ----
[2019-12-09T18:36:17.338Z] [2019-12-09 18:36:09 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2019-12-09T18:36:17.338Z] [2019-12-09 18:36:09 +0000] [1] [INFO] Listening at: http://0.0.0.0:8001 (1)
[2019-12-09T18:36:17.338Z] [2019-12-09 18:36:09 +0000] [1] [INFO] Using worker: sync
[2019-12-09T18:36:17.338Z] [2019-12-09 18:36:09 +0000] [21] [INFO] Booting worker with pid: 21
[2019-12-09T18:36:17.338Z] [2019-12-09 18:36:09 +0000] [22] [INFO] Booting worker with pid: 22
[2019-12-09T18:36:17.338Z] [2019-12-09 18:36:10 +0000] [23] [INFO] Booting worker with pid: 23
[2019-12-09T18:36:17.338Z] [2019-12-09 18:36:10 +0000] [24] [INFO] Booting worker with pid: 24
[2019-12-09T18:36:17.338Z] Exception in thread eapm conf updater:
[2019-12-09T18:36:17.338Z] Traceback (most recent call last):
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2019-12-09T18:36:17.338Z]     self.run()
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/utils/threading.py", line 79, in run
[2019-12-09T18:36:17.338Z]     rval = self._function(*self._args, **self._kwargs)
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/conf/__init__.py", line 402, in update_config
[2019-12-09T18:36:17.338Z]     new_version, new_config, next_run = transport.get_config(agent.config.config_version, keys)
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/transport/http.py", line 116, in get_config
[2019-12-09T18:36:17.338Z]     response = self.http.urlopen(
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
[2019-12-09T18:36:17.338Z]     response = conn.urlopen(method, u.request_uri, **kw)
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
[2019-12-09T18:36:17.338Z]     return wrapped(*args, **kwargs)
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 654, in urlopen
[2019-12-09T18:36:17.338Z]     conn = self._get_conn(timeout=pool_timeout)
[2019-12-09T18:36:17.338Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
[2019-12-09T18:36:17.339Z]     return conn or self._new_conn()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 228, in _new_conn
[2019-12-09T18:36:17.339Z]     conn = self.ConnectionCls(
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 112, in __init__
[2019-12-09T18:36:17.339Z]     _HTTPConnection.__init__(self, *args, **kw)
[2019-12-09T18:36:17.339Z] TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
[2019-12-09T18:36:17.339Z] Exception in thread eapm conf updater:
[2019-12-09T18:36:17.339Z] Traceback (most recent call last):
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2019-12-09T18:36:17.339Z]     self.run()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/utils/threading.py", line 79, in run
[2019-12-09T18:36:17.339Z]     rval = self._function(*self._args, **self._kwargs)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/conf/__init__.py", line 402, in update_config
[2019-12-09T18:36:17.339Z]     new_version, new_config, next_run = transport.get_config(agent.config.config_version, keys)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/transport/http.py", line 116, in get_config
[2019-12-09T18:36:17.339Z]     response = self.http.urlopen(
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
[2019-12-09T18:36:17.339Z]     response = conn.urlopen(method, u.request_uri, **kw)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
[2019-12-09T18:36:17.339Z]     return wrapped(*args, **kwargs)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 654, in urlopen
[2019-12-09T18:36:17.339Z]     conn = self._get_conn(timeout=pool_timeout)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
[2019-12-09T18:36:17.339Z]     return conn or self._new_conn()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 228, in _new_conn
[2019-12-09T18:36:17.339Z]     conn = self.ConnectionCls(
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 112, in __init__
[2019-12-09T18:36:17.339Z]     _HTTPConnection.__init__(self, *args, **kw)
[2019-12-09T18:36:17.339Z] TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
[2019-12-09T18:36:17.339Z] Exception in thread eapm conf updater:
[2019-12-09T18:36:17.339Z] Traceback (most recent call last):
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2019-12-09T18:36:17.339Z]     self.run()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/utils/threading.py", line 79, in run
[2019-12-09T18:36:17.339Z]     rval = self._function(*self._args, **self._kwargs)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/conf/__init__.py", line 402, in update_config
[2019-12-09T18:36:17.339Z]     new_version, new_config, next_run = transport.get_config(agent.config.config_version, keys)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/transport/http.py", line 116, in get_config
[2019-12-09T18:36:17.339Z]     response = self.http.urlopen(
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
[2019-12-09T18:36:17.339Z]     response = conn.urlopen(method, u.request_uri, **kw)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
[2019-12-09T18:36:17.339Z]     return wrapped(*args, **kwargs)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 654, in urlopen
[2019-12-09T18:36:17.339Z]     conn = self._get_conn(timeout=pool_timeout)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
[2019-12-09T18:36:17.339Z]     return conn or self._new_conn()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 228, in _new_conn
[2019-12-09T18:36:17.339Z]     conn = self.ConnectionCls(
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 112, in __init__
[2019-12-09T18:36:17.339Z]     _HTTPConnection.__init__(self, *args, **kw)
[2019-12-09T18:36:17.339Z] TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
[2019-12-09T18:36:17.339Z] Exception in thread eapm conf updater:
[2019-12-09T18:36:17.339Z] Traceback (most recent call last):
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2019-12-09T18:36:17.339Z]     self.run()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/utils/threading.py", line 79, in run
[2019-12-09T18:36:17.339Z]     rval = self._function(*self._args, **self._kwargs)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/conf/__init__.py", line 402, in update_config
[2019-12-09T18:36:17.339Z]     new_version, new_config, next_run = transport.get_config(agent.config.config_version, keys)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/transport/http.py", line 116, in get_config
[2019-12-09T18:36:17.339Z]     response = self.http.urlopen(
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
[2019-12-09T18:36:17.339Z]     response = conn.urlopen(method, u.request_uri, **kw)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
[2019-12-09T18:36:17.339Z]     return wrapped(*args, **kwargs)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 654, in urlopen
[2019-12-09T18:36:17.339Z]     conn = self._get_conn(timeout=pool_timeout)
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
[2019-12-09T18:36:17.339Z]     return conn or self._new_conn()
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 228, in _new_conn
[2019-12-09T18:36:17.339Z]     conn = self.ConnectionCls(
[2019-12-09T18:36:17.339Z]   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 112, in __init__
[2019-12-09T18:36:17.339Z]     _HTTPConnection.__init__(self, *args, **kw)
[2019-12-09T18:36:17.339Z] TypeError: __init__() got an unexpected keyword argument 'assert_hostname'
```

**Comment by kuisathaverat** [comment]
sounds like a python 3 issue

**Comment by kuisathaverat** [comment]
changing the containers to `python:3.7`those errors disappeared but the test errors persist

**Comment by kuisathaverat** [comment]
```
Failed to submit message: "Unable to reach APM Server: __init__() got an unexpected keyword argument 'assert_hostname' (url: http://apm-server:8200/intake/v2/events)"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/elasticapm/transport/http.py", line 76, in send
    response = self.http.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 136, in call_if_sampling
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 654, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 274, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 228, in _new_conn
    conn = self.ConnectionCls(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 112, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'assert_hostname'

During handling of the above exception, another exception occurred:
```

**Comment by kuisathaverat** [comment]
I track it to this issue https://github.com/elastic/apm-agent-python/issues/570 seems pretty similar

**Comment by kuisathaverat** [comment]
confirmed, we cannot set `ELASTIC_APM_VERIFY_SERVER_CERT` to any value it breaks the Python agent on 5.1 and 4.1
