### ISSUE TITLE
Kibana OSS container does not start correctly - Error: Unknown configuration key(s): "xpack.apm.serviceMapEnabled".

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#749]
We detected on ITs that Python is not running the test on the test that starts Kibana, the following error is shown in the Kibana logs

```
{"type":"log","@timestamp":"2020-01-30T03:18:11+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: apm_oss"}
{"type":"log","@timestamp":"2020-01-30T03:18:11+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: dashboard_embeddable_container"}
{"type":"log","@timestamp":"2020-01-30T03:18:11+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: dev_tools"}
{"type":"log","@timestamp":"2020-01-30T03:18:11+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: eui_utils"}
{"type":"log","@timestamp":"2020-01-30T03:18:11+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: kibana_legacy"}
{"type":"log","@timestamp":"2020-01-30T03:18:11+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: status_page"}
{"type":"log","@timestamp":"2020-01-30T03:18:12+00:00","tags":["fatal","root"],"pid":6,"message":"{ Error: Unknown configuration key(s): \"xpack.apm.serviceMapEnabled\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/usr/share/kibana/src/core/server/legacy/config/ensure_valid_configuration.js:46:11) code: 'InvalidConfig', processExitCode: 64, cause: undefined }"}

 FATAL  Error: Unknown configuration key(s): "xpack.apm.serviceMapEnabled". Check for spelling errors and ensure that expected plugins are installed.

{"type":"log","@timestamp":"2020-01-30T03:18:16+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: apm_oss"}
{"type":"log","@timestamp":"2020-01-30T03:18:16+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: dashboard_embeddable_container"}
{"type":"log","@timestamp":"2020-01-30T03:18:16+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: dev_tools"}
{"type":"log","@timestamp":"2020-01-30T03:18:16+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: eui_utils"}
{"type":"log","@timestamp":"2020-01-30T03:18:16+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: kibana_legacy"}
{"type":"log","@timestamp":"2020-01-30T03:18:16+00:00","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: status_page"}
{"type":"log","@timestamp":"2020-01-30T03:18:17+00:00","tags":["fatal","root"],"pid":6,"message":"{ Error: Unknown configuration key(s): \"xpack.apm.serviceMapEnabled\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/usr/share/kibana/src/core/server/legacy/config/ensure_valid_configuration.js:46:11) code: 'InvalidConfig', processExitCode: 64, cause: undefined }"}

 FATAL  Error: Unknown configuration key(s): "xpack.apm.serviceMapEnabled". Check for spelling errors and ensure that expected plugins are installed.
```

**Comment by kuisathaverat** [comment]
I think is related to https://github.com/elastic/apm-integration-testing/pull/742

**Comment by kuisathaverat** [comment]
we have to not enable the flag on Kibana OSS
