### ISSUE TITLE
Failure in starting stack services

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-integration-testing#884]
Reported by @eyalkoren 

```
[2020-07-13T11:45:19.553Z] Successfully tagged apm-integration-testing_agent-java-spring:latest
[2020-07-13T11:45:19.553Z] Building agent-java-spring ... done
[2020-07-13T11:46:06.286Z] Creating localtesting_8.0.0_elasticsearch ... 
[2020-07-13T11:46:06.286Z] Creating localtesting_8.0.0_elasticsearch ... done
[2020-07-13T11:46:38.434Z] Creating localtesting_8.0.0_kibana        ... 
[2020-07-13T11:46:38.434Z] Creating localtesting_8.0.0_kibana        ... done
[2020-07-13T11:47:46.194Z] 
[2020-07-13T11:47:46.194Z] ERROR: for apm-server  Container "ba027b67a9de" is unhealthy.
[2020-07-13T11:47:46.194Z] Encountered errors while bringing up the project.
[2020-07-13T11:47:46.194Z] Starting stack services..
[2020-07-13T11:47:46.194Z] 
[2020-07-13T11:47:46.194Z] Traceback (most recent call last):
[2020-07-13T11:47:46.194Z]   File "scripts/compose.py", line 25, in <module>
[2020-07-13T11:47:46.194Z]     main()
[2020-07-13T11:47:46.194Z]   File "scripts/compose.py", line 21, in main
[2020-07-13T11:47:46.194Z]     setup()
[2020-07-13T11:47:46.194Z]   File "/var/lib/jenkins/workspace/ration-tests-selector-mbp_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 180, in __call__
[2020-07-13T11:47:46.194Z]     self.args.func()
[2020-07-13T11:47:46.194Z]   File "/var/lib/jenkins/workspace/ration-tests-selector-mbp_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 644, in start_handler
[2020-07-13T11:47:46.194Z]     self.run_docker_compose_process(docker_compose_cmd + up_params)
[2020-07-13T11:47:46.194Z]   File "/var/lib/jenkins/workspace/ration-tests-selector-mbp_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 414, in run_docker_compose_process
[2020-07-13T11:47:46.194Z]     subprocess.check_call(docker_compose_cmd)
[2020-07-13T11:47:46.194Z]   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
[2020-07-13T11:47:46.194Z]     raise CalledProcessError(retcode, cmd)
[2020-07-13T11:47:46.194Z] subprocess.CalledProcessError: Command '['docker-compose', '-f', '/var/lib/jenkins/workspace/ration-tests-selector-mbp_master/src/github.com/elastic/apm-integration-testing/docker-compose.yml', '--no-ansi', '--log-level', 'ERROR', 'up', '-d', '--quiet-pull']' returned non-zero exit status 1.
[2020-07-13T11:47:46.194Z] Makefile:62: recipe for target 'start-env' failed
[2020-07-13T11:47:46.194Z] make[1]: *** [start-env] Error 1
[2020-07-13T11:47:46.194Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/ration-tests-selector-mbp_master/src/github.com/elastic/apm-integration-testing'
[2020-07-13T11:47:46.194Z] Makefile:73: recipe for target 'env-agent-java' failed
[2020-07-13T11:47:46.194Z] make: *** [env-agent-java] Error 2
script returned exit code 2
```

Full log: https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-integration-tests-selector-mbp/pipelines/master/runs/9491/steps/89/log/

**Comment by cachedout** [comment]
May be related to a broken build of Kibana...

**Comment by cachedout** [comment]
This is fixed upstream.
