### ISSUE TITLE
APM Java test are failing to build the Docker image

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#901]
```
[2020-08-28T03:15:07.537Z] python3 scripts/compose.py start 8.0.0   --apm-server-build https://github.com/elastic/apm-server.git@master --build-parallel --java-agent-version=master   --no-apm-server-dashboards   --no-apm-server-self-instrument   --no-kibana   --with-agent-java-spring   --force-build   --no-xpack-secure   --apm-log-level=debug
...
[2020-08-28T03:19:47.193Z] 
[2020-08-28T03:19:47.193Z] ERROR: for agent-java-spring  (<Service: agent-java-spring>, 'The command \'/bin/sh -c ./maven-package.sh "${JAVA_AGENT_BUILT_VERSION}"\' returned a non-zero code: 1')
[2020-08-28T03:19:47.193Z] Service 'agent-java-spring' failed to build: The command '/bin/sh -c ./maven-package.sh "${JAVA_AGENT_BUILT_VERSION}"' returned a non-zero code: 1
[2020-08-28T03:19:47.193Z] Starting stack services..
[2020-08-28T03:19:47.193Z] 
[2020-08-28T03:19:47.193Z] Traceback (most recent call last):
[2020-08-28T03:19:47.193Z]   File "scripts/compose.py", line 25, in <module>
[2020-08-28T03:19:47.193Z]     main()
[2020-08-28T03:19:47.193Z]   File "scripts/compose.py", line 21, in main
[2020-08-28T03:19:47.193Z]     setup()
[2020-08-28T03:19:47.193Z]   File "/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 181, in __call__
[2020-08-28T03:19:47.193Z]     self.args.func()
[2020-08-28T03:19:47.193Z]   File "/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 636, in start_handler
[2020-08-28T03:19:47.193Z]     self.run_docker_compose_process(docker_compose_build + build_services)
[2020-08-28T03:19:47.193Z]   File "/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 423, in run_docker_compose_process
[2020-08-28T03:19:47.193Z]     subprocess.check_call(docker_compose_cmd)
[2020-08-28T03:19:47.193Z]   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
[2020-08-28T03:19:47.193Z]     raise CalledProcessError(retcode, cmd)
[2020-08-28T03:19:47.193Z] subprocess.CalledProcessError: Command '['docker-compose', '-f', '/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/docker-compose.yml', '--no-ansi', '--log-level', 'ERROR', 'build', '--pull', '--no-cache', '--parallel', 'apm-server', 'agent-java-spring']' returned non-zero exit status 1.
[2020-08-28T03:19:47.193Z] Makefile:66: recipe for target 'start-env' failed
[2020-08-28T03:19:47.193Z] make[1]: *** [start-env] Error 1
[2020-08-28T03:19:47.193Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing'
[2020-08-28T03:19:47.193Z] Makefile:77: recipe for target 'env-agent-java' failed
[2020-08-28T03:19:47.193Z] make: *** [env-agent-java] Error 2
```

```
[2020-08-28T03:15:09.598Z] python3 scripts/compose.py start 8.0.0   --apm-server-build https://github.com/elastic/apm-server.git@master --oss --build-parallel --java-agent-version=master   --no-apm-server-dashboards   --no-apm-server-self-instrument   --no-kibana   --with-agent-java-spring   --force-build   --no-xpack-secure   --apm-log-level=debug
...
[2020-08-28T03:19:07.821Z] ERROR: for agent-java-spring  (<Service: agent-java-spring>, 'The command \'/bin/sh -c ./maven-package.sh "${JAVA_AGENT_BUILT_VERSION}"\' returned a non-zero code: 1')
[2020-08-28T03:19:07.822Z] Service 'agent-java-spring' failed to build: The command '/bin/sh -c ./maven-package.sh "${JAVA_AGENT_BUILT_VERSION}"' returned a non-zero code: 1
[2020-08-28T03:19:07.822Z] Starting stack services..
[2020-08-28T03:19:07.822Z] 
[2020-08-28T03:19:07.822Z] Traceback (most recent call last):
[2020-08-28T03:19:07.822Z]   File "scripts/compose.py", line 25, in <module>
[2020-08-28T03:19:07.822Z]     main()
[2020-08-28T03:19:07.822Z]   File "scripts/compose.py", line 21, in main
[2020-08-28T03:19:07.822Z]     setup()
[2020-08-28T03:19:07.822Z]   File "/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 181, in __call__
[2020-08-28T03:19:07.822Z]     self.args.func()
[2020-08-28T03:19:07.822Z]   File "/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 636, in start_handler
[2020-08-28T03:19:07.822Z]     self.run_docker_compose_process(docker_compose_build + build_services)
[2020-08-28T03:19:07.822Z]   File "/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/scripts/modules/cli.py", line 423, in run_docker_compose_process
[2020-08-28T03:19:07.822Z]     subprocess.check_call(docker_compose_cmd)
[2020-08-28T03:19:07.822Z]   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
[2020-08-28T03:19:07.822Z]     raise CalledProcessError(retcode, cmd)
[2020-08-28T03:19:07.822Z] subprocess.CalledProcessError: Command '['docker-compose', '-f', '/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing/docker-compose.yml', '--no-ansi', '--log-level', 'ERROR', 'build', '--pull', '--no-cache', '--parallel', 'agent-java-spring', 'apm-server']' returned non-zero exit status 1.
[2020-08-28T03:19:07.822Z] Makefile:66: recipe for target 'start-env' failed
[2020-08-28T03:19:07.822Z] make[1]: *** [start-env] Error 1
[2020-08-28T03:19:07.822Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/tegration-test-downstream_master/src/github.com/elastic/apm-integration-testing'
[2020-08-28T03:19:07.822Z] Makefile:77: recipe for target 'env-agent-java' failed
[2020-08-28T03:19:07.822Z] make: *** [env-agent-java] Error 2
```

**Comment by kuisathaverat** [comment]
`JAVA_AGENT_BUILT_VERSION` is empty

**Comment by kuisathaverat** [comment]
It needs Java 11 to compile since a few days

**Comment by kuisathaverat** [comment]
but the master seems broken right now

```
[ERROR] COMPILATION ERROR : 
[ERROR] /agent/apm-agent-java/apm-agent-plugins/apm-jdk-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/HttpRequestHeadersInstrumentation.java:[73,26] error: cannot find symbol
  symbol:   method of(Map<String,List<String>>,(x,y)->true)
  location: class HttpHeaders
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project apm-jdk-httpclient-plugin: Compilation failure
[ERROR] /agent/apm-agent-java/apm-agent-plugins/apm-jdk-httpclient-plugin/src/main/java/co/elastic/apm/agent/httpclient/HttpRequestHeadersInstrumentation.java:[73,26] error: cannot find symbol
[ERROR]   symbol:   method of(Map<String,List<String>>,(x,y)->true)
[ERROR]   location: class HttpHeaders
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-jdk-httpclient-plugin
```
