### ISSUE TITLE
APM Server build is broken

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#932]
```
[2020-09-23T08:36:38.430Z] ./build/linux/bin/mage -compile=build/linux/mage
[2020-09-23T08:37:25.288Z] 2020/09/23 08:37:17 exec: go list -m
[2020-09-23T08:37:25.288Z] Generated fields.yml for apm-server to /go/src/github.com/elastic/apm-server/build/fields/fields.yml
[2020-09-23T08:37:25.288Z] Generated fields.yml for apm-server to /go/src/github.com/elastic/apm-server/build/fields/fields.all.yml
[2020-09-23T08:37:51.846Z] /go/src/github.com/elastic/apm-server/model/modeldecoder/v2/decoder.go:339:41: t.Context.Request.Headers.Val.Values undefined (type http.Header has no field or method Values)
[2020-09-23T08:37:51.846Z] panic: packages load error
[2020-09-23T08:37:51.846Z] 
[2020-09-23T08:37:51.846Z] goroutine 1 [running]:
[2020-09-23T08:37:51.846Z] main.genV2()
[2020-09-23T08:37:51.846Z] 	/go/src/github.com/elastic/apm-server/model/modeldecoder/generator/cmd/main.go:53 +0x1b3
[2020-09-23T08:37:51.846Z] main.main()
[2020-09-23T08:37:51.846Z] 	/go/src/github.com/elastic/apm-server/model/modeldecoder/generator/cmd/main.go:44 +0x20
[2020-09-23T08:37:51.846Z] exit status 2
[2020-09-23T08:37:51.846Z] main.go:21: running "go": exit status 1
[2020-09-23T08:37:51.846Z] make: Leaving directory '/go/src/github.com/elastic/apm-server'
[2020-09-23T08:37:51.846Z] make: *** [Makefile:126: go-generate] Error 1
```

**Comment by graphaelli** [comment]
Update to go 1.14 will fix this
